# This file overrides settings from `.config/mise.toml`.
# Because `.config/mise.toml` is continuously overwritten by `mise cookiecutter`,
# any project-specific modifications should be placed here to avoid being clobbered.

[tools]
node = 'latest'
python = '3.12'
uv = 'latest'

[tasks.test]
run = '''
#!/usr/bin/env bash
if [ "$(mise envi)" = "github" ]; then
    sudo apt-get update && sudo apt-get install -y ffmpeg sox
fi
python -m pytest test_vclz.py
'''

[tasks.run-on-sources]
quiet = true
run = '''
#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail
tool=${1:?missing executable}
eval "glob=(${2:?missing source glob})"
shift 2
command_args=$*
set -- $(
    git ls-files -- "${glob[@]}" \
        | grep --invert-match --extended-regexp --file <(
            grep --invert-match '^#' .biobuddies/autoformat-excludes
        ) \
        | xargs grep -I -l "" 2>/dev/null \
        || [[ $? -eq 1 ]]
)
[[ $# -eq 0 ]] && exit 0
[[ -z $command_args ]] || set -- $command_args "$@"
"$tool" "$@"
'''
